# Generated by Django 3.0.8 on 2020-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del proyecto')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor/es o empresa creadora')),
                ('foto', models.ImageField(upload_to='Trabajos', verbose_name='Foto del proyect')),
                ('enlace', models.URLField(blank=True, null=True, verbose_name='Enlace del proyecto')),
                ('fechafin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin de proyecto')),
            ],
            options={
                'verbose_name': 'trabajo',
                'verbose_name_plural': 'trabajos',
            },
        ),
    ]
