# Generated by Django 3.0.8 on 2020-07-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='descripcion',
            field=models.TextField(max_length=600, null=True, verbose_name='Descripción del proyecto'),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='foto',
            field=models.ImageField(upload_to='Trabajos', verbose_name='Foto del proyecto'),
        ),
    ]
