# Generated by Django 3.0.8 on 2020-07-23 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nombreyredes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nombre',
            new_name='Titulo',
        ),
    ]
