# Generated by Django 3.0.8 on 2020-07-28 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nombreyredes', '0002_auto_20200723_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enlace',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'redes sociales'},
        ),
        migrations.AlterModelOptions(
            name='titulo',
            options={'verbose_name_plural': 'nombre y rol'},
        ),
    ]
