# Generated by Django 3.0.8 on 2020-09-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20200727_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacion',
            name='formacion',
            field=models.CharField(max_length=200, verbose_name='Formación recibida'),
        ),
    ]
