# Generated by Django 3.0.8 on 2020-09-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20200924_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacion',
            name='formacion',
            field=models.TextField(max_length=200, verbose_name='Formación recibida'),
        ),
    ]
