# Generated by Django 3.0.8 on 2020-09-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20200924_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosdeinteres',
            name='dato',
            field=models.CharField(max_length=80, verbose_name='Dato de interes'),
        ),
    ]
